### ISSUE TITLE
똑똑

### ISSUE THREAD

**Issue by kwj1270** [seongaeee/Vue-Study#1]
여기가 뷰 맛집이라는데? 사실인가요

**Comment by seongaeee** [comment]
맛없어요

**Comment by kwj1270** [comment]
주방장 나와

**Comment by Jihun22** [comment]
맛집 ㅎㅇ

**Comment by kwj1270** [comment]
@Jihun22 
![image](https://user-images.githubusercontent.com/50267433/117929460-d1d67c80-b337-11eb-96f6-3ab867943a28.png)

**Comment by seongaeee** [comment]
이 귀한 곳에 누추한 분이...
아 거꾸로 썼네요 :)

**Comment by kwj1270** [comment]
@Jihun22 형 들었죠?
